package com.bahj.smelt.plugin.builtin.basegui.event;

import com.bahj.smelt.util.event.Event;

/**
 * The type of events generated by the base GUI plugin.
 * @author Zachary Palmer
 */
public abstract class BaseGUIEvent implements Event {
}
