package com.bahj.smelt.model.syntax.datamodel.parser;

/**
 * Represents a parsing rule in the Smelt data model language.
 * @author Zachary Palmer
 *
 * @param <T> The type of value generated by this parse rule.
 */
public interface ParseRule<T> {
	public T parse(ParseContext context);
}
