package com.bahj.smelt.model.event;

import com.bahj.smelt.model.SmeltLogicalModel;
import com.bahj.smelt.util.event.Event;

/**
 * The type of event generated by the Smelt model.
 * 
 * @author Zachary Palmer
 */
public abstract class SmeltModelEvent implements Event {
    private SmeltLogicalModel model;

    public SmeltModelEvent(SmeltLogicalModel model) {
        super();
        this.model = model;
    }

    /**
     * Retrieves the model which generated this event.
     * @return The model which generated this event.
     */
    public SmeltLogicalModel getModel() {
        return model;
    }
}
